added remote manager tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,17 +41,41 @@ executors:
 
 
 commands:
+
+  setup_manager:
+    steps:
+      - run: |
+          if [[ -z "${CLOUDIFY_HOST}" ]]; then
+              exit 1
+          fi
+      - run: |
+          if [[ -z "${CLOUDIFY_TENANT}" ]]; then
+              exit 1
+          fi
+      - run: |
+          if [[ -z "${CLOUDIFY_TOKEN}" ]]; then
+              exit 1
+          fi
+      - run: |
+          response=$(curl --write-out '%{http_code}' --silent --insecure --header "Tenant: ${CLOUDIFY_TENANT}" --header "Authentication-Token: ${CLOUDIFY_TOKEN}" https://$CLOUDIFY_HOST/api/v3.1/status --output /dev/null)
+          if [[ $response != 200 ]]; then
+              echo "Failed to get manager status";
+              exit 1
+          fi
+      - run: pip3 install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/refs/heads/master.zip
+      - run: git submodule update --init --recursive --remote
+
   prepare_test_manager:
     steps:
-      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es aws_access_key_id=${aws_access_key_id} -es aws_secret_access_key=${aws_secret_access_key} -es kubernetes_token=$null_value -es kubernetes_config=$null_value --yum-package python-netaddr --yum-package git -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn*)  ~/project/plugin.yaml
-      - run: ecosystem-test upload-plugin -PN utilities
-      - run: ecosystem-test upload-plugin -PN ansible
-      - run: ecosystem-test upload-plugin -PN kubernetes
+      - run: ecosystem-test prepare-remote-test-manager -es aws_access_key_id=${aws_access_key_id} -es aws_secret_access_key=${aws_secret_access_key} -es kubernetes_token=$null_value -es kubernetes_config=$null_value -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn*)  ~/project/plugin.yaml
+      - run: ecosystem-test remote-upload-plugin -PN utilities
+      - run: ecosystem-test remote-upload-plugin -PN ansible
+      - run: ecosystem-test remote-upload-plugin -PN kubernetes
 
   run_eks_helm_test:
     steps:
       - run: git clone https://github.com/cloudify-community/blueprint-examples.git
-      - run: ecosystem-test local-blueprint-test -b blueprint-examples/kubernetes/helm-eks/blueprint.yaml -i eks_cluster_name=helm-plugin-test-$CIRCLE_BUILD_NUM --test-id=helm-eks --on-failure=uninstall-force --timeout=5400
+      - run: ecosystem-test remote-blueprint-test -b blueprint-examples/kubernetes/helm-eks/blueprint.yaml -i eks_cluster_name=helm-plugin-test-$CIRCLE_BUILD_NUM --test-id=helm-eks --on-failure=uninstall-force --timeout=5400
 
 jobs:
   integration_tests_py3:
@@ -75,18 +99,14 @@ workflows:
           <<: *unittest-post-steps
       - node/validate_version_job
       - node/validate_documentation_job
-# 
-      - wagonorb/wagon
-      # - wagonorb/wagon:
-      #     filters:
-      #       branches:
-      #         only: /([0-9\.]*\-build|master|dev)/
-# 
-      - wagonorb/wagon_311
-      # - wagonorb/wagon_311:
-      #     filters:
-      #       branches:
-      #         only: /([0-9\.]*\-build|master|dev)/
+      - wagonorb/wagon:
+          filters:
+            branches:
+              only: /([0-9\.]*\-build|master|dev)/
+      - wagonorb/wagon_311:
+          filters:
+            branches:
+              only: /([0-9\.]*\-build|master|dev)/
       - wagonorb/arch64_wagon:
           filters:
             branches:
@@ -103,8 +123,8 @@ workflows:
           requires:
             - wagonorb/wagon
             - wagonorb/wagon_311
-            # - wagonorb/rhel_wagon
-            # - wagonorb/arch64_wagon
+            - wagonorb/rhel_wagon
+            - wagonorb/arch64_wagon
           filters:
             branches:
               only: /([0-9\.]*\-build|master|dev)/
