build bundle,release and docs with py36 executor

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -105,6 +105,16 @@ commands:
             git submodule init
             git submodule update --remote --recursive
       - run:
+          name: Set Python
+          command: |
+            if ! pyenv -v &> /dev/null
+            then
+                echo "pyenv could not be found"
+                exit
+            else
+                pyenv global 3.6.5
+            fi
+      - run:
           name: Download pip
           command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
       - run:
@@ -136,6 +146,16 @@ commands:
           command: |
             git submodule init
             git submodule update --remote --recursive
+      - run:
+          name: Set Python
+          command: |
+            if ! pyenv -v &> /dev/null
+            then
+                echo "pyenv could not be found"
+                exit
+            else
+                pyenv global 3.6.5
+            fi
       - run:
           name: Download pip
           command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
@@ -219,13 +239,21 @@ commands:
 
   release_plugin:
     steps:
-      - attach_workspace:
-          at: workspace
       - run:
           name: "Pull Submodules"
           command: |
             git submodule init
             git submodule update --remote --recursive
+      - run:
+          name: Set Python
+          command: |
+            if ! pyenv -v &> /dev/null
+            then
+                echo "pyenv could not be found"
+                exit
+            else
+                pyenv global 3.6.5
+            fi
       - run:
           name: Download pip
           command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
@@ -260,6 +288,16 @@ commands:
           command: |
             git submodule init
             git submodule update --remote --recursive
+      - run:
+          name: Set Python
+          command: |
+            if ! pyenv -v &> /dev/null
+            then
+                echo "pyenv could not be found"
+                exit
+            else
+                pyenv global 3.6.5
+            fi
       - run:
           name: Download pip
           command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
@@ -300,19 +338,19 @@ jobs:
       - run_unittest_py36
 
   py3_compat:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - check_py3_compat
 
   validate_version:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - validate_version
 
   validate_documentation:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - validate_documentation
@@ -330,19 +368,19 @@ jobs:
       - generate_rhel_py27py36_wagon
 
   build-bundle:
-    executor: wagon_generator
+    executor: py36
     steps:
       - checkout
       - build_archive
 
   release:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - release_plugin
 
   merge_docs:
-    executor: py27
+    executor: py36
     steps:
       - checkout
       - merge_docs
